server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pns?useUnicode=true&characterEncoding=UTF-8&useJDBC49CompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
    host: 101.43.253.15
    port: 6379
    password: root
    client-name: jedis
    jedis:
      pool:
        max-active: 16
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  tencent:
    secretId: AKIDmrqa3HIiFj3xmQozwe7LK4Zp8QWN3dz5
    secretKey: 1qlUzIOJ8j4FH7hCUX9jGcjaDblgQvQh
    bucket: ap-beijing
    bucketName: wyx-1303917755
#    path: https://wyx-1303917755.cos.ap-beijing.myqcloud.com
    path: https://img.weiyuexin.top
    qianzui: img
    qianzui-file: file
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

